### ISSUE TITLE
how to convert string to boolean ?

### ISSUE THREAD

**Issue by lmk07** [iwasrobbed/Objective-C-CheatSheet#22]
im having string value as "True"

NSString *rootuser = "True"

this i want convert into boolean true and push it into object like below.

{
rootuser : true
}

thanks.

**Comment by iwasrobbed** [comment]
Hi there - you can just do a simple comparison like rootuser == “True” to get a boolean result or even use the string isEqual checks like https://developer.apple.com/documentation/foundation/nsstring/1407803-isequaltostring

please look around on StackOverflow for more info since it’s a bit outside of this project’s  scope
